
CREATE TABLE Genre(
	genre_name		TEXT,
	genre_desc		TEXT,
	PRIMARY KEY (genre_name)
);

INSERT INTO Genre VALUES
('Action',null),
('Adventure',null),
('Cars',null),
('Comedy',null),
('Dementia',null),
('Demons',null),
('Drama',null),
('Ecchi',null),
('Fantasy',null),
('Game',null),
('Harem',null),
('Hentai',null),
('Historical',null),
('Horror',null),
('Josei',null),
('Kids',null),
('Magic',null),
('Martial Arts',null),
('Mecha',null),
('Military',null),
('Music',null),
('Mystery',null),
('Parody',null),
('Police',null),
('Psychological',null),
('Romance',null),
('Samurai',null),
('School',null),
('Sci-Fi',null),
('Seinen',null),
('Shoujo',null),
('Shoujo Ai',null),
('Shounen',null),
('Shounen Ai',null),
('Slice of Life',null),
('Space',null),
('Sports',null),
('Super Power',null),
('Supernatural',null),
('Thriller',null),
('Vampire',null),
('Yaoi',null),
('Yuri',null);