
CREATE TABLE Licensor(
	lic_id		INT,
	name		TEXT,
	PRIMARY KEY (lic_id)
);

INSERT INTO Licensor VALUES
(1,'4Kids Entertainment'),
(2,'Active'),
(3,'Adult Source Media'),
(4,'ADV Films'),
(5,'Anchor Bay Films'),
(6,'Anime Midstream'),
(7,'AnimEigo'),
(8,'Aniplex of America'),
(9,'Bandai'),
(10,'Bandai Entertainment'),
(11,'Bandai Namco Games'),
(12,'Bandai Visual USA'),
(13,'bilibili'),
(14,'Capcom'),
(15,'Central Park Media'),
(16,'Cinelicious Pics'),
(17,'Crimson Star Media'),
(18,'Critical Mass Video'),
(19,'Crunchyroll'),
(20,'Dentsu Entertainment USA'),
(21,'DiC Entertainment'),
(22,'Discotek Media'),
(23,'DreamWorks'),
(24,'Enoki Films'),
(25,'feel.'),
(26,'Flatiron Film Company'),
(27,'Funimation'),
(28,'Geneon Entertainment USA'),
(29,'Geneon Universal Entertainment'),
(30,'GKIDS'),
(31,'Haoliners Animation League'),
(32,'Hasbro'),
(33,'JapanAnime'),
(34,'Kadokawa Pictures USA'),
(35,'Ketchup Entertainment'),
(36,'Kitty Media'),
(37,'Konami'),
(38,'Maiden Japan'),
(39,'Manga Entertainment'),
(40,'Marvel Entertainment'),
(41,'Media Blasters'),
(42,'Miramax Films'),
(43,'Nelvana'),
(44,'Nintendo of America'),
(45,'NIS America Inc.'),
(46,'Nozomi Entertainment'),
(47,'NuTech Digital'),
(48,'NYAV Post'),
(49,'OLM Digital'),
(50,'Pied Piper'),
(51,'Ponycan USA'),
(52,'Saban Entertainment'),
(53,'Sentai Filmworks'),
(54,'Shout! Factory'),
(55,'SoftCel Pictures'),
(56,'Sony Music Entertainment'),
(57,'Sony Pictures Entertainment'),
(58,'Super Techno Arts'),
(59,'Synch-Point'),
(60,'Tencent Animation'),
(61,'The Pokemon Company International'),
(62,'TOKYOPOP'),
(63,'Urban Vision'),
(64,'Viz Media'),
(65,'Voyager Entertainment'),
(66,'Walt Disney Studios'),
(67,'Warner Bros.');