
CREATE TABLE Licensor(
	lic_id		INT,
	name		VARCHAR(50) NOT NULL,
	PRIMARY KEY (lic_id)
);

INSERT INTO Licensor VALUES
	(1,'4Kids Entertainment'),
	(2,'ADV Films'),
	(3,'Anchor Bay Films'),
	(4,'Anime Midstream'),
	(5,'AnimEigo'),
	(6,'Aniplex of America'),
	(7,'Bandai'),
	(8,'Bandai Entertainment'),
	(9,'Bandai Namco Games'),
	(10,'Bandai Visual USA'),
	(11,'bilibili'),
	(12,'Capcom'),
	(13,'Central Park Media'),
	(14,'Crimson Star Media'),
	(15,'Crunchyroll'),
	(16,'Dentsu Entertainment USA'),
	(17,'DiC Entertainment'),
	(18,'Discotek Media'),
	(19,'DreamWorks'),
	(20,'Enoki Films'),
	(21,'feel.'),
	(22,'Flatiron Film Company'),
	(23,'Funimation'),
	(24,'Geneon Entertainment USA'),
	(25,'Geneon Universal Entertainment'),
	(26,'GKIDS'),
	(27,'Hasbro'),
	(28,'Kadokawa Pictures USA'),
	(29,'Ketchup Entertainment'),
	(30,'Konami'),
	(31,'Maiden Japan'),
	(32,'Manga Entertainment'),
	(33,'Marvel Entertainment'),
	(34,'Media Blasters'),
	(35,'Miramax Films'),
	(36,'Nelvana'),
	(37,'Nintendo of America'),
	(38,'NIS America Inc.'),
	(39,'Nozomi Entertainment'),
	(40,'NYAV Post'),
	(41,'OLM Digital'),
	(42,'Pied Piper'),
	(43,'Ponycan USA'),
	(44,'Saban Entertainment'),
	(45,'Sentai Filmworks'),
	(46,'Shout! Factory'),
	(47,'Sony Music Entertainment'),
	(48,'Sony Pictures Entertainment'),
	(49,'Super Techno Arts'),
	(50,'Synch-Point'),
	(51,'The Pokemon Company International'),
	(52,'TOKYOPOP'),
	(53,'Urban Vision'),
	(54,'Viz Media'),
	(55,'Voyager Entertainment'),
	(56,'Walt Disney Studios'),
	(57,'Warner Bros.');